### ISSUE TITLE
Failed to read GIOP message in ClientGIOPConnection

### ISSUE THREAD

**Issue by mihir842in** [JacORB/JacORB#209] opened 2018-01-15 09:49 UTC
When a server method call takes more than 10 seconds, we are seeing following error on client side. Here, jacorb v3.8 is used and there are no jacorb properties set/passed explicitely on client side. We checked the default values from jacorb_properties.template, but none are set to 10 seconds.
Any idea on this error or cause?
				
19:49:28,992 ERROR (ClientMessageReceptor22) [org.jacorb.giop.conn] Failed to read GIOP message in ClientGIOPConnection to xxx.xx.x.xxx:10070 (5cbfc35d): org.omg.CORBA.COMM_FAILURE: read() did not return any data  vmcid: 0x0  minor code: 0  completed: No
	at org.jacorb.orb.etf.StreamConnectionBase.read(StreamConnectionBase.java:149) [jacorb.jar:3.8]
	at org.jacorb.orb.giop.GIOPConnection.getMessage(GIOPConnection.java:462) [jacorb.jar:3.8]
	at org.jacorb.orb.giop.GIOPConnection.receiveMessagesLoop(GIOPConnection.java:550) [jacorb.jar:3.8]
	at org.jacorb.orb.giop.GIOPConnection.receiveMessages(GIOPConnection.java:537) [jacorb.jar:3.8]
	at org.jacorb.orb.giop.MessageReceptor.doWork(MessageReceptor.java:69) [jacorb.jar:3.8]
	at org.jacorb.util.threadpool.ConsumerTie.run(ConsumerTie.java:60) [jacorb.jar:3.8]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_66]	
19:49:28,992 WARN  (ClientMessageReceptor22) [org.jacorb.giop.conn] Abnormal connection termination. Lost 1 outstanding replie(s)!
19:49:28,992 INFO  (ClientMessageReceptor22) [org.jacorb.orb.iiop.ClientIIOPConnection] Client-side TCP transport to xxx.xx.x.xxx:10070 closed.

**Comment by rnc** [comment] 2018-01-15 10:23
This looks like the the https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#read(byte[],%20int,%20int) did not return any data. 

- Do you have debug logs from server and client? 
- Can you reproduce it every time?
- Can you supply a test case demonstrating the issue ? 
- What does a wireshark log show ?

**Comment by rnc** [comment] 2020-07-01 20:52
I'm closing this as there is not enough information to reproduce.

**Closed by rnc** 2020-07-01 20:52 UTC
