### ISSUE TITLE
Do we need to restart ORB every time when we sign program?

### ISSUE THREAD

**Issue by tejaswinir7** [JacORB/JacORB#272] opened 2021-06-14 05:56 UTC
Hi All,

below are the steps:
Hi
Below are the exact Steps:

1) add CA public key to key store file
​ 2) key store file is provided to ORB during init.
3) Another program signed with CA, is contacted
4) Authentication is done using public key of CA and it is successful
5) Now change the certificate on second program. certificate on second program is changed, which is also signed by same CA.
but Second program is disconnected from first program
6) Handshake this time fails.
9) If ORB is restarted on First program (without making any change to keystore or certificates) handshake is successful. second program will connect to first program.

we dnt want to restart ORB on each Program signing with CA. Please suggest.

**Comment by rnc** [comment] 2021-08-30 12:21
Duplicate of #270

**Closed by rnc** 2021-08-30 12:21 UTC
